### ISSUE TITLE
关于运行程序中的一些问题

### ISSUE THREAD

**Issue by pq-dong** [hirCodd/AutoAddProblem#2]
因为oj版本更新，页面元素的定位不同会导致在定位元素的时候找不到元素，从而出现错误‘raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: ’
提供可能的一种解决方法：
1. 打开浏览器的开发者模式选项，重新查看元素位置，并修改代码
2. 同时还有可能出现上传测试数据不成功的问题，这时需要注意file_input的路径和file_input的定位不是button而是在button下边的input元素。
总结一下：因为oj版本变化，会在定位元素的时候出现各种问题，需要自己仔细查找元素位置

**Comment by moremind** [comment]
这个由于qduoj开发后有更新了较多版本，所以厚些问题，有兴趣的话，可以自己改一下代码，基本没有什么太大问题就可以搞定。
