### ISSUE TITLE
你好，链接失效了，可以补发一下吗

### ISSUE THREAD

**Issue by suings** [hirCodd/AutoAddProblem#3]

**Comment by moremind** [comment]
可以的



Best Regards!
在 suings <notifications@github.com>，2019年11月4日 22:14写道：

**Comment by moremind** [comment]
你好，由于百度网盘将我的test-case删除，现在需要你去自己去下载对应的数据，联系我的邮箱，可以把下载url给你。

**Comment by suings** [comment]
你好，我的邮箱是 1357424862@qq.com ，麻烦您有空时将下载链接发给我。

**Comment by Pipepw** [comment]
您好，请问可以麻烦您发一下下载链接吗，我的邮箱是pipepw@126.com

**Comment by moremind** [comment]
我能把bt文件发送上去@Pipepw

**Comment by moremind** [comment]
链接：https://pan.baidu.com/s/1thPX3QR6EFJ-U-Dhq9MUzg 
提取码：2333

**Comment by shadowdai-netizen** [comment]
链接又失效啦

**Comment by shadowdai-netizen** [comment]
可以麻烦发我一份嘛？，1933908466@qq.com

**Comment by zzRicardo** [comment]
可以麻烦楼主有空的时候也发我一份么！谢谢！
我的邮箱是：1375648126@qq.com

**Comment by luxuncang** [comment]
可以麻烦楼主有空的时候也发我一份么！多谢！2635886314@qq.com

**Comment by moremind** [comment]
您好！
    这是题库的种子文件！

Best Regards！

发件人: ***@***.***>
发送时间: 2021年4月12日 15:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [hirCodd/AutoAddProblem] 你好，链接失效了，可以补发一下吗 (#3)


***@***.******@***.***>

―

**Comment by MrRobotsAA** [comment]
可以麻烦楼主在有空的时候也发我一份嘛！多谢！我的邮箱是 axuhongbo@126.com

**Comment by moremind** [comment]
链接: https://pan.baidu.com/s/16hBaKpI3ltImxA2q4-Paqg?pwd=nkdf 提取码: nkdf 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by moremind** [comment]
链接: https://pan.baidu.com/s/1ug7XIaOKxHPyZHV4iNxS8Q?pwd=uyj9 提取码: uyj9 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by dage233** [comment]
麻烦楼主在有空的时候也发我一份嘛多谢！我的邮箱是 1019088083@qq.com
